### ISSUE TITLE
undefined: tls.ClientHelloInfo

### ISSUE THREAD

**Issue by mekhalleh** [xiam/hyperfox#4]
Hello,

When I launch "go get github.com/xiam/hyperfox" I obtain the following result:

# github.com/xiam/hyperfox/proxy
/usr/lib/go/src/pkg/github.com/xiam/hyperfox/proxy/main.go:301: undefined: tls.ClientHelloInfo
/usr/lib/go/src/pkg/github.com/xiam/hyperfox/proxy/main.go:325: unknown tls.Config field 'GetCertificate' in struct literal

Have you an idea ?

I work on Debian in multi release mode and the go version is "go1.3.2 linux/amd64"

Thanks in advance ;)

**Comment by xiam** [comment]
Looks like your go version does not have the `tls.ClientHelloInfo` type, it should compile fine with go1.4. Hyperfox requires some C code (for SQLite) so you'll also need the gcc and the build-essentials packages.

**Comment by dkarter** [comment]
OS X: I had the exact same issue when running go 1.3.3. I've upgraded my go version to 

```bash
$ go version
go version go1.4 darwin/amd64
```

I am now getting the following error:

```bash
$ go get github.com/xiam/hyperfox
# github.com/xiam/hyperfox/proxy
Dropbox/Developer/gocode/src/github.com/xiam/hyperfox/proxy/main.go:34: import /Users/dkarter/Dropbox/Developer/gocode/pkg/darwin_amd64/github.com/xiam/hyperfox/util/otf.a: object is [darwin amd64 go1.3.3 X:precisestack] expected [darwin amd64 go1.4 X:precisestack]
```

I am using Homebrew to manage/install go versions. It looks like it's somehow using another an older version of Go for Hyperfox. Any ideas on how to fix this?

**Comment by xiam** [comment]
Confirmed, I was not aware that `tls.ClientHelloInfo` was introduced in `go1.4`.

Compilation on recent OSX is a bit complicated but not impossible.

To spare you the building effort I've uploaded [Hyperfox for OSX x64](https://hyperfox.org/files/hyperfox-0.9-darwin-x64.bin) in binary format and also a [arpspoof](https://hyperfox.org/files/arpspoof-2.4-darwin-x64.bin) binary I built myself, since it's very difficult to install dsniff with macports or brew due to a series of bugs.

Instructions for building on a mac will be posted soon (need some time to clean my notes).

@dkarter To fix your problem delete the `/Users/dkarter/Dropbox/Developer/gocode/pkg/darwin_amd64/github.com/xiam/hyperfox/util/otf.a` file and try again.
